version: '3.8'
services:
  postgres:
    image: postgres
    volumes:
      - /Users/armin/databases/postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passme
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: passme
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: passme
    ports:
      - 8180:8080
    depends_on:
      - postgres